-- AlterEnum
ALTER TYPE "NotificationEntityType" ADD VALUE 'OUTFIT';

-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'OUTFIT_BOARD_ACTIVITY';
ALTER TYPE "NotificationType" ADD VALUE 'OUTFIT_READY_TO_LOCK';
ALTER TYPE "NotificationType" ADD VALUE 'OUTFIT_LOCKED';
ALTER TYPE "NotificationType" ADD VALUE 'OUTFIT_INVITED';
ALTER TYPE "NotificationType" ADD VALUE 'OUTFIT_SHARED';
ALTER TYPE "NotificationType" ADD VALUE 'OUTFIT_MADE_PUBLIC';
