import path from "node:path";

import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "./src"),
      "@test": path.resolve(import.meta.dirname, "./src/testing"),
    },
  },
  test: {
    coverage: {
      provider: "v8",
      include: [
        "src/features/auth/utils/safeRedirect.ts",
        "src/features/auth/utils/getDefaultRoute.ts",
        "src/features/auth/utils/accountSuspended.ts",
        "src/features/auth/components/AccountSuspendedScreen.tsx",
        "src/features/auth/components/CaptchaChallenge.tsx",
        "src/features/auth/hooks/**/*.{ts,tsx}",
        "src/features/auth/api/oauthApi.ts",
        "src/features/auth/api/serverAuth.ts",
        "src/features/auth/components/ConnectedAccounts.tsx",
        "src/features/auth/components/UnlinkAccountModal.tsx",
        "src/features/auth/components/AddPhoneNumberBanner.tsx",
        "src/features/auth/components/NotAShopperNotice.tsx",
        "src/features/auth/components/ContinueWithOAuthButtons.tsx",
        "src/features/auth/components/OAuthCallbackScreen.tsx",
        "src/components/ProductGridSkeleton.tsx",
        "src/components/HomeSectionError.tsx",
        "src/components/SiteFooter.tsx",
        "src/components/AccountMenu.tsx",
        "src/components/DashboardSidebarLink.tsx",
        "src/components/FollowersModal.tsx",
        "src/components/DashboardMobileNavBar.tsx",
        "src/components/DashboardNavCustomizeSheet.tsx",
        "src/components/dashboardMobileNav.ts",
        "src/components/useDashboardMobileNav.ts",
        "src/components/useNavPreferences.ts",
        "src/components/useDashboardNav.ts",
        "src/features/outfit-build/components/BuyBuildPanel.tsx",
        "src/features/creator-dashboard/earnings/components/EarningsSection.tsx",
        "src/components/SidebarPendingNavContext.tsx",
        "src/shared/components/CategoryTypeFilters.tsx",
        "src/shared/hooks/usePendingSelection.ts",
        "src/shared/hooks/useTabSearchParam.ts",
        "src/shared/lib/replaceUrlSearchParams.ts",
        "src/shared/hooks/useOptimisticFollow.ts",
        "src/features/landing/context/CategorySelectionContext.tsx",
        "src/features/landing/components/CategoryResults.tsx",
        "src/features/shop/components/ShopResults.tsx",
        "src/features/shop/components/ThriftOnlyToggle.tsx",
        "src/features/explore/components/ExploreFeed.tsx",
        "src/features/explore/components/PostCardSkeleton.tsx",
        "src/features/brand-profile/components/BrandProfile.tsx",
        "src/features/product-detail/api/getProductDetailServer.ts",
        "src/features/products/api/getProductsServer.ts",
        "src/features/creator-leaderboard/components/CreatorLeaderboardTabs.tsx",
        "src/features/explore/components/FeedFilterTabs.tsx",
        "src/features/explore/components/ExploreSidebarNav.tsx",
        "src/features/explore/components/AddPostButton.tsx",
        "src/features/explore/components/PostCard.tsx",
        "src/features/explore/components/PostCarousel.tsx",
        "src/features/explore/components/PostCardHeader.tsx",
        "src/features/explore/components/PostCommentsSection.tsx",
        "src/features/explore/components/PostDetailModal.tsx",
        "src/features/explore/components/PostGridCard.tsx",
        "src/features/explore/components/PostReportMenu.tsx",
        "src/features/explore/components/PostTagPill.tsx",
        "src/features/explore/components/Sidebar.tsx",
        "src/features/explore/components/ReportContentModal.tsx",
        "src/features/explore/components/ConfirmDeleteCommentModal.tsx",
        "src/features/product-detail/components/ProductDetail.tsx",
        "src/features/product-detail/components/ThriftPurchaseConfirmModal.tsx",
        "src/features/product-detail/components/ShippingInfo.tsx",
        "src/features/users/components/UserList.tsx",
        "src/features/users/components/EditOwnProfileCard.tsx",
        "src/features/users/hooks/useHandleAvailability.ts",
        "src/features/users/hooks/useUpdateOwnProfile.ts",
        "src/features/notifications/components/SiteNotificationBell.tsx",
        "src/features/landing/components/ProductCard.tsx",
        "src/features/wishlist/hooks/useToggleWishlist.ts",
        "src/features/product-reviews/components/RatingSummary.tsx",
        "src/features/product-reviews/components/ReviewCard.tsx",
        "src/features/brand-dashboard/api/brandOverviewApi.ts",
        "src/features/brand-dashboard/api/brandOverviewSchemas.ts",
        "src/features/brand-dashboard/components/BrandOverview.tsx",
        "src/features/brand-dashboard/hooks/useBrandOverview.ts",
        "src/features/brand-dashboard/products/components/DiscountModal.tsx",
        "src/features/brand-dashboard/products/components/ProductsSection.tsx",
        "src/features/brand-dashboard/products/components/EditProductForm.tsx",
        "src/features/brand-dashboard/products/components/ThriftListingFields.tsx",
        "src/features/brand-dashboard/tag-reviews/components/TagReviewsSection.tsx",
        "src/features/brand-dashboard/tag-reviews/components/TagReviewCard.tsx",
        "src/features/brand-dashboard/tag-reviews/components/RejectTagModal.tsx",
        "src/features/brand-dashboard/tag-reviews/components/BrandTagPolicyCard.tsx",
        "src/features/brand-dashboard/tag-reviews/api/tagReviewApi.ts",
        "src/features/brand-dashboard/tag-reviews/api/tagReviewSchemas.ts",
        "src/features/brand-dashboard/tag-reviews/constants/tagReview.constants.ts",
        "src/features/brand-dashboard/tag-reviews/hooks/useTagReviewQueue.ts",
        "src/features/brand-dashboard/tag-reviews/hooks/usePrefetchTagReviewQueues.ts",
        "src/features/brand-dashboard/tag-reviews/hooks/useTagReviewPendingCount.ts",
        "src/features/brand-dashboard/tag-reviews/hooks/useReviewTagActions.ts",
        "src/features/brand-profile/hooks/useInfiniteBrandProducts.ts",
        "src/features/brand-profile/api/brandProfileApi.ts",
        "src/features/search/components/ExploreSearchBox.tsx",
        "src/features/search/components/SearchResults.tsx",
        "src/features/search/components/ExploreSearchResults.tsx",
        "src/features/creator-profile/components/CreatorProfile.tsx",
        "src/features/search/hooks/useExploreAutocomplete.ts",
        "src/features/collections/components/CollectionDetail.tsx",
        "src/features/brands/**/*.{ts,tsx}",
        "src/features/creator-profile/api/creatorProfileApi.ts",
        "src/features/creator-profile/api/creatorProfileSchemas.ts",
        "src/features/creator-profile/components/**/*.{ts,tsx}",
        "src/features/creator-profile/hooks/**/*.{ts,tsx}",
        "src/features/creator-profile/index.ts",
        "src/features/creator-dashboard/earnings/api/commissionApi.ts",
        "src/features/creator-dashboard/earnings/api/commissionSchemas.ts",
        "src/features/creator-dashboard/api/creatorOverviewApi.ts",
        "src/features/creator-dashboard/api/creatorOverviewSchemas.ts",
        "src/features/creator-dashboard/api/creatorDashboardApi.ts",
        "src/features/creator-dashboard/api/creatorDashboardSchemas.ts",
        "src/features/creator-dashboard/share-links/api/creatorLinksApi.ts",
        "src/features/creator-dashboard/share-links/api/creatorLinksSchemas.ts",
        "src/features/creator-dashboard/looks/api/creatorLooksApi.ts",
        "src/features/creator-dashboard/looks/api/creatorLooksSchemas.ts",
        "src/features/creator-dashboard/badges/components/AchievementBadgeCard.tsx",
        "src/features/creator-dashboard/components/ApplyAsCreatorButton.tsx",
        "src/features/creator-dashboard/earnings/components/CommissionStatusBadge.tsx",
        "src/features/creator-dashboard/components/CreatorOverview.tsx",
        "src/features/creator-dashboard/components/CreatorStatusGate.tsx",
        "src/features/creator-dashboard/earnings/components/EarningsLedgerRow.tsx",
        "src/features/creator-dashboard/earnings/components/EarningsSection.tsx",
        "src/features/creator-dashboard/earnings/components/EarningsSummaryTiles.tsx",
        "src/features/creator-dashboard/looks/components/EditPostForm.tsx",
        "src/features/creator-dashboard/looks/components/EditPostModal.tsx",
        "src/features/creator-dashboard/looks/components/LayoutPicker.tsx",
        "src/features/creator-dashboard/looks/components/PostModal.tsx",
        "src/features/creator-dashboard/looks/components/ProductTagPicker.tsx",
        "src/features/creator-dashboard/looks/utils/taggedProductSizeErrors.ts",
        "src/features/creator-dashboard/looks/utils/tagReviewLabels.ts",
        "src/features/creator-dashboard/share-links/components/ShareLinkRow.tsx",
        "src/features/creator-dashboard/share-links/components/ShareProductPicker.tsx",
        "src/features/creator-dashboard/share-links/components/ShareSection.tsx",
        "src/features/creator-dashboard/progress/components/XpMultiplierBanner.tsx",
        "src/features/creator-dashboard/hooks/useCreatorOverview.ts",
        "src/features/creator-dashboard/earnings/hooks/useEarningsSummary.ts",
        "src/features/creator-dashboard/progress/hooks/useGamificationSocket.ts",
        "src/features/creator-dashboard/progress/components/ProgressSection.tsx",
        "src/features/creator-dashboard/progress/components/LevelProgressCard.tsx",
        "src/features/creator-dashboard/badges/components/BadgeCollectionSection.tsx",
        "src/features/creator-dashboard/challenges/components/ChallengesSection.tsx",
        "src/features/creator-dashboard/looks/hooks/useLookDetail.ts",
        "src/features/creator-dashboard/share-links/hooks/useMyCreatorLinks.ts",
        "src/features/creator-dashboard/earnings/hooks/useMyEarnings.ts",
        "src/features/creator-dashboard/looks/hooks/useTaggableProducts.ts",
        "src/features/creator-dashboard/looks/schemas/lookForm.schema.ts",
        "src/features/creator-dashboard/share-links/utils/creatorLinksCacheUpdate.ts",
        "src/features/creator-dashboard/index.ts",
        "src/features/messaging/utils/groupEventText.ts",
        "src/features/messaging/components/SystemMessageLine.tsx",
        "src/features/messaging/components/GroupAvatar.tsx",
        "src/features/messaging/components/ContactPicker.tsx",
        "src/features/messaging/components/NewGroupModal.tsx",
        "src/features/messaging/components/GroupInfoPanel.tsx",
        "src/features/explore/components/SuggestedCreatorRow.tsx",
        "src/features/explore/components/SuggestedCreatorsModal.tsx",
        "src/features/notifications/utils/resolveNotificationHref.ts",
        "src/app/(dashboard)/requireDashboardSession.ts",
        "src/features/auth/api/userSchemas.ts",
        "src/features/explore/utils/commentCacheUpdate.ts",
        "src/features/explore/utils/feedCacheUpdate.ts",
        "src/features/explore/utils/trendingRank.ts",
        "src/features/explore/components/CommentThread.tsx",
        "src/app/internal/revalidate/route.ts",
        "src/shared/components/DeferredMount.tsx",
        "src/shared/components/AppImage.tsx",
        "src/shared/lib/responsiveImage.ts",
        "src/shared/lib/contentSecurityPolicy.ts",
        "src/shared/lib/serverApiClient.ts",
        "src/shared/lib/apiOrigin.ts",
        "src/shared/lib/heicImage.ts",
        "src/features/bank-accounts/components/AddBankAccountModal.tsx",
        "src/features/bank-accounts/components/BankAccountsList.tsx",
        "src/features/bank-accounts/components/BankAccountCard.tsx",
        "src/features/withdraw/components/WithdrawRequestForm.tsx",
        "src/features/withdraw/components/WithdrawRequestStatusBadge.tsx",
        "src/features/withdraw/components/WithdrawSectionSkeleton.tsx",
        "src/features/withdraw/components/WithdrawPolicyPanel.tsx",
        "src/features/brand-dashboard/wallet/components/WalletSummaryTiles.tsx",
        "src/features/chat-settings/components/ChatAvailabilitySettings.tsx",
        "src/shared/lib/chatApi.ts",
        "src/features/messaging/components/ConversationList.tsx",
        "src/features/messaging/components/MessageThread.tsx",
        "src/features/messaging/components/MessagesPageLayout.tsx",
        "src/shared/seo/jsonLd.tsx",
        "src/shared/seo/metadata.ts",
        "src/shared/seo/routes.ts",
        "src/shared/seo/siteConfig.ts",
        "src/shared/seo/Breadcrumbs.tsx",
        "src/features/marketing/components/FaqAccordion.tsx",
        "src/features/marketing/components/MarketingHero.tsx",
        "src/features/marketing/components/FeatureGrid.tsx",
        "src/features/marketing/components/StepList.tsx",
        "src/features/marketing/components/MarketingCta.tsx",
        "src/components/motion/Reveal.tsx",
        "src/components/motion/Stagger.tsx",
        "src/features/categories/api/tastePreferencesApi.ts",
        "src/features/categories/hooks/useTastePreferences.ts",
        "src/features/categories/utils/visibleTasteCategories.ts",
        "src/features/categories/utils/resolveStoredTasteSlugs.ts",
        "src/features/categories/utils/tasteSlugs.ts",
        "src/features/landing/utils/resolveTasteCategories.ts",
        "src/features/landing/utils/scrollToTasteResults.ts",
        "src/shared/hooks/useIsHydrated.ts",
        "src/features/landing/components/CustomizeTasteModal.tsx",
        "src/features/support/schemas/support.schema.ts",
        "src/features/support/components/SupportRequestForm.tsx",
        "src/features/pwa/**/*.{ts,tsx}",
        "src/features/product-tour/**/*.{ts,tsx}",
        "src/app/manifest.ts",
        "src/features/addresses/api/addressApi.ts",
        "src/features/addresses/api/addressSchemas.ts",
        "src/features/addresses/hooks/**/*.{ts,tsx}",
        "src/features/addresses/components/AddressList.tsx",
        "src/features/addresses/components/AddressCard.tsx",
        "src/features/addresses/components/AddressFormModal.tsx",
        "src/features/addresses/components/SavedAddressPicker.tsx",
        "src/features/checkout/components/CheckoutSummary.tsx",
        "src/features/checkout/components/CheckoutForm.tsx",
        "src/features/checkout/components/BuyNowCouponForm.tsx",
        "src/features/checkout/utils/buildBuyNowCart.ts",
        "src/features/cart/components/CouponForm.tsx",
        "src/features/checkout/hooks/useCheckout.ts",
        "src/features/checkout/hooks/useBuyNowCouponPreview.ts",
        "src/features/payments/hooks/useInitiatePayment.ts",
        "src/features/payments/components/PaymentCallbackScreen.tsx",
        "src/features/orders/components/OrderDetailBody.tsx",
        "src/features/orders/components/PendingPaymentPanel.tsx",
        "src/features/orders/hooks/useCancelOrder.ts",
        "src/features/explore/hooks/useLikeLook.ts",
        "src/features/explore/hooks/useSaveLook.ts",
        "src/features/explore/hooks/useFollowCreator.ts",
        "src/features/explore/hooks/useSuggestedCreators.ts",
        "src/features/explore/hooks/useDeleteComment.ts",
        "src/features/explore/hooks/useReportContent.ts",
        "src/features/explore/utils/offlineActionTypes.ts",
        "src/features/explore/utils/offlineQueueableToggle.ts",
        "src/features/explore/utils/offlineActionHandlers.ts",
        "src/features/explore/utils/lookPermalink.ts",
        "src/features/explore/utils/forYouHint.ts",
        "src/features/explore/hooks/usePostCardState.ts",
        "src/features/explore/components/PostActionsRow.tsx",
        "src/shared/hooks/usePendingPhotos.ts",
        "src/app/(dashboard)/share-target/ShareTargetComposer.tsx",
        "src/features/explore/hooks/useInfiniteExploreFeed.ts",
        "src/features/explore/api/exploreFeedQueryKey.ts",
        "src/features/explore/hooks/usePublicLook.ts",
        "src/features/creator-profile/hooks/useInfiniteCreatorLooks.ts",
        "src/features/brands/api/serverBrands.ts",
        "src/features/brand-profile/api/getBrandProfileServerPublic.ts",
        "src/features/creator-profile/api/getCreatorProfileServerPublic.ts",
        "src/features/outfit-build/utils/**/*.ts",
        "src/features/outfit-build/components/BuildCardMessage.tsx",
        "src/features/outfit-build/components/MyBuildsPage.tsx",
        "src/features/outfit-build/components/SlotCard.tsx",
        "src/features/outfit-build/components/PostAsLookPanel.tsx",
        "src/features/outfit-build/components/PublicBuildsFeed.tsx",
        "src/features/outfit-build/components/PublicBuildCardView.tsx",
        "src/features/outfit-build/components/PublicBuildFiltersBar.tsx",
        "src/features/outfit-build/components/BoardActions.tsx",
        "src/features/outfit-build/components/PublicBuildDetailView.tsx",
        "src/features/outfit-build/components/BuildDetailModal.tsx",
        "src/features/outfit-build/components/BuildReactionsBar.tsx",
        "src/features/outfit-build/components/BuildComments.tsx",
        "src/features/outfit-build/hooks/useBuildSocial.ts",
        "src/features/outfit-build/api/outfitSocialApi.ts",
        "src/features/explore/hooks/useExploreTabs.ts",
        "src/features/outfit-build/components/PublishLookModal.tsx",
        "src/features/outfit-build/components/BoardPhotosPanel.tsx",
        "src/features/outfit-build/components/BuildCoverGrid.tsx",
        "src/features/outfit-build/components/PublicBuildPhotos.tsx",
        "src/features/outfit-build/components/PublishedBuildView.tsx",
        "src/features/outfit-offers/components/**/*.tsx",
        "src/features/outfit-offers/hooks/**/*.ts",
        "src/features/outfit-offers/api/**/*.ts",
        "src/features/creator-dashboard/looks/hooks/useMaxTaggedProducts.ts",
        "src/features/saved-sizes/**/*.{ts,tsx}",
        "src/shared/hooks/useFeatureFlag.ts",
        "src/i18n/localeCookie.ts",
        "src/i18n/useChosenLanguage.ts",
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
    },
    projects: [
      {
        extends: true,
        test: {
          name: "unit",
          include: ["src/**/*.test.{ts,tsx}"],
          exclude: ["src/**/*.integration.test.{ts,tsx}"],
          environment: "jsdom",
          setupFiles: ["./src/testing/setup.ts"],
        },
      },
      {
        extends: true,
        test: {
          name: "integration",
          include: ["src/**/*.integration.test.{ts,tsx}"],
          environment: "jsdom",
          setupFiles: ["./src/testing/setup.ts", "./src/testing/integration/setup.ts"],
          testTimeout: 10000,
          pool: "forks",
          maxWorkers: 1,
          execArgv: ["--max-old-space-size=3072"],
          vmMemoryLimit: "384mb",
        },
      },
    ],
  },
});
