import path from "node:path";

import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "./src"),
      "@test": path.resolve(import.meta.dirname, "./src/testing"),
    },
  },
  test: {
    coverage: {
      provider: "v8",
      include: [
        "src/features/auth/utils/safeRedirect.ts",
        "src/features/auth/utils/getDefaultRoute.ts",
        "src/features/auth/components/CaptchaChallenge.tsx",
        "src/features/auth/hooks/**/*.{ts,tsx}",
        "src/features/auth/api/oauthApi.ts",
        "src/features/auth/components/ConnectedAccounts/**/*.{ts,tsx}",
        "src/features/auth/components/AddPhoneNumberBanner.tsx",
        "src/features/auth/components/ContinueWithOAuthButtons.tsx",
        "src/features/auth/components/OAuthCallbackScreen/**/*.{ts,tsx}",
        "src/components/ProductGridSkeleton.tsx",
        "src/components/AccountMenu.tsx",
        "src/components/DashboardSidebarLink.tsx",
        "src/components/DashboardMobileNavBar.tsx",
        "src/components/DashboardNavCustomizeSheet.tsx",
        "src/components/dashboardMobileNav.ts",
        "src/components/useDashboardMobileNav.ts",
        "src/components/useNavPreferences.ts",
        "src/components/useDashboardNav.ts",
        "src/components/SidebarPendingNavContext.tsx",
        "src/shared/components/CategoryTypeFilters.tsx",
        "src/features/creator-leaderboard/components/CreatorLeaderboardTabs.tsx",
        "src/features/explore/components/FeedFilterTabs.tsx",
        "src/features/explore/components/AddPostButton.tsx",
        "src/features/product-detail/components/ShippingInfo.tsx",
        "src/features/users/components/UserList.tsx",
        "src/features/notifications/SiteNotificationBell.tsx",
        "src/features/landing/components/ProductCard/index.tsx",
        "src/features/product-reviews/components/RatingSummary.tsx",
        "src/features/product-reviews/components/ReviewCard.tsx",
        "src/features/brand-dashboard/api/brandOverviewApi.ts",
        "src/features/brand-dashboard/api/brandOverviewSchemas.ts",
        "src/features/brand-dashboard/components/BrandOverview.tsx",
        "src/features/brand-dashboard/components/BrandOrderRow.tsx",
        "src/features/brand-dashboard/hooks/useBrandOverview.ts",
        "src/features/brand-profile/hooks/useInfiniteBrandProducts.ts",
        "src/features/brand-profile/api/brandProfileApi.ts",
        "src/features/search/components/ExploreSearchBox.tsx",
        "src/features/search/hooks/useExploreAutocomplete.ts",
        "src/features/brands/**/*.{ts,tsx}",
        "src/features/creator-profile/api/creatorProfileApi.ts",
        "src/features/creator-profile/api/creatorProfileSchemas.ts",
        "src/features/creator-profile/components/**/*.{ts,tsx}",
        "src/features/creator-profile/hooks/**/*.{ts,tsx}",
        "src/features/creator-profile/index.ts",
        "src/features/creator-dashboard/api/commissionApi.ts",
        "src/features/creator-dashboard/api/commissionSchemas.ts",
        "src/features/creator-dashboard/api/creatorOverviewApi.ts",
        "src/features/creator-dashboard/api/creatorOverviewSchemas.ts",
        "src/features/creator-dashboard/api/creatorDashboardApi.ts",
        "src/features/creator-dashboard/api/creatorDashboardSchemas.ts",
        "src/features/creator-dashboard/api/creatorLinksApi.ts",
        "src/features/creator-dashboard/api/creatorLinksSchemas.ts",
        "src/features/creator-dashboard/api/creatorLooksApi.ts",
        "src/features/creator-dashboard/api/creatorLooksSchemas.ts",
        "src/features/creator-dashboard/components/AchievementBadgeCard.tsx",
        "src/features/creator-dashboard/components/ApplyAsCreatorButton.tsx",
        "src/features/creator-dashboard/components/CommissionStatusBadge.tsx",
        "src/features/creator-dashboard/components/CreatorOverview.tsx",
        "src/features/creator-dashboard/components/CreatorStatusGate.tsx",
        "src/features/creator-dashboard/components/EarningsLedgerRow.tsx",
        "src/features/creator-dashboard/components/EarningsSection.tsx",
        "src/features/creator-dashboard/components/EarningsSummaryTiles.tsx",
        "src/features/creator-dashboard/components/EditPostForm.tsx",
        "src/features/creator-dashboard/components/EditPostModal.tsx",
        "src/features/creator-dashboard/components/PostModal.tsx",
        "src/features/creator-dashboard/components/ProductTagPicker.tsx",
        "src/features/creator-dashboard/utils/taggedProductSizeErrors.ts",
        "src/features/creator-dashboard/components/ShareLinkRow.tsx",
        "src/features/creator-dashboard/components/ShareProductPicker.tsx",
        "src/features/creator-dashboard/components/ShareSection.tsx",
        "src/features/creator-dashboard/components/XpMultiplierBanner.tsx",
        "src/features/creator-dashboard/hooks/useCreatorOverview.ts",
        "src/features/creator-dashboard/hooks/useEarningsSummary.ts",
        "src/features/creator-dashboard/hooks/useGamificationSocket.ts",
        "src/features/creator-dashboard/hooks/useLookDetail.ts",
        "src/features/creator-dashboard/hooks/useMyCreatorLinks.ts",
        "src/features/creator-dashboard/hooks/useMyEarnings.ts",
        "src/features/creator-dashboard/hooks/useTaggableProducts.ts",
        "src/features/creator-dashboard/schemas/lookForm.schema.ts",
        "src/features/creator-dashboard/utils/creatorLinksCacheUpdate.ts",
        "src/features/creator-dashboard/index.ts",
        "src/features/explore/components/SuggestedCreatorRow.tsx",
        "src/features/explore/components/SuggestedCreatorsModal.tsx",
        "src/features/notifications/resolveNotificationHref.ts",
        "src/features/auth/api/userSchemas.ts",
        "src/features/explore/utils/commentCacheUpdate.ts",
        "src/features/explore/components/CommentThread.tsx",
        "src/shared/lib/contentSecurityPolicy.ts",
        "src/shared/lib/apiOrigin.ts",
        "src/shared/lib/heicImage.ts",
        "src/features/bank-accounts/components/AddBankAccountModal.tsx",
        "src/features/withdraw/components/WithdrawRequestForm.tsx",
        "src/features/withdraw/components/WithdrawRequestStatusBadge.tsx",
        "src/features/withdraw/components/WithdrawSectionSkeleton.tsx",
        "src/features/chat-settings/ChatAvailabilitySettings.tsx",
        "src/shared/lib/chatApi.ts",
        "src/features/messaging/ConversationList.tsx",
        "src/features/messaging/MessageThread.tsx",
        "src/shared/seo/jsonLd.tsx",
        "src/shared/seo/metadata.ts",
        "src/shared/seo/routes.ts",
        "src/shared/seo/siteConfig.ts",
        "src/shared/seo/Breadcrumbs.tsx",
        "src/features/marketing/components/FaqAccordion.tsx",
        "src/features/categories/api/tastePreferencesApi.ts",
        "src/features/categories/hooks/useTastePreferences.ts",
        "src/features/categories/lib/visibleTasteCategories.ts",
        "src/features/landing/components/TasteCategories/CustomizeTasteModal.tsx",
        "src/features/support/schemas/support.schema.ts",
        "src/features/support/components/SupportRequestForm.tsx",
        "src/features/pwa/**/*.{ts,tsx}",
        "src/app/manifest.ts",
      ],
      thresholds: {
        lines: 85,
        functions: 85,
        branches: 85,
        statements: 85,
      },
    },
    projects: [
      {
        extends: true,
        test: {
          name: "unit",
          include: ["src/**/*.test.{ts,tsx}"],
          exclude: ["src/**/*.integration.test.{ts,tsx}"],
          environment: "jsdom",
          setupFiles: ["./src/testing/setup.ts"],
        },
      },
      {
        extends: true,
        test: {
          name: "integration",
          include: ["src/**/*.integration.test.{ts,tsx}"],
          environment: "jsdom",
          setupFiles: ["./src/testing/setup.ts", "./src/testing/integration/setup.ts"],
          testTimeout: 10000,
        },
      },
    ],
  },
});
