import { type SidebarIcon, type SidebarNavItem } from "@outfiqe/components";
import {
  Activity,
  Award,
  BanknoteArrowUp,
  BarChart3,
  Blocks,
  Building2,
  ClipboardList,
  CreditCard,
  Crown,
  Fingerprint,
  Flag,
  GalleryHorizontal,
  Gauge,
  IdCard,
  Images,
  KanbanSquare,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LifeBuoy,
  ListChecks,
  MapPin,
  Megaphone,
  MessageSquareWarning,
  Package,
  Percent,
  PiggyBank,
  QrCode,
  Ruler,
  ScrollText,
  Settings2,
  Shapes,
  ShieldAlert,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  SlidersHorizontal,
  Star,
  Tags,
  TicketPercent,
  ToggleRight,
  TrendingUp,
  Trophy,
  UserCog,
  UserRound,
  Users,
  VenetianMask,
  Wallet,
  Zap,
} from "lucide-react";

import { type PlatformNavGroupKey, type PlatformNavItem } from "./AdminSidebar.utils";

type CrmSubItem = SidebarNavItem & { permissionKey: string | null; requiresLinkedBrand?: boolean };

export const CRM_SUB_ITEMS: CrmSubItem[] = [
  { id: "crm-overview", href: "/crm", label: "Overview", icon: LayoutGrid, permissionKey: null },
  {
    id: "crm-partners",
    href: "/crm/partners",
    label: "Partners",
    icon: Users,
    permissionKey: "accounts:read",
    requiresLinkedBrand: true,
  },
  {
    id: "crm-customers",
    href: "/crm/customers",
    label: "Customers",
    icon: UserRound,
    permissionKey: "customers:read",
    requiresLinkedBrand: true,
  },
  {
    id: "crm-contacts",
    href: "/crm/contacts",
    label: "Contacts",
    icon: IdCard,
    permissionKey: "contacts:read",
  },
  {
    id: "crm-pipeline",
    href: "/crm/pipeline",
    label: "Pipeline",
    icon: KanbanSquare,
    permissionKey: "pipeline:read",
  },
  {
    id: "crm-tasks",
    href: "/crm/tasks",
    label: "Tasks",
    icon: ListChecks,
    permissionKey: "tasks:read",
  },
  {
    id: "crm-support",
    href: "/crm/support",
    label: "Support",
    icon: LifeBuoy,
    permissionKey: "tickets:read",
  },
  {
    id: "crm-reports",
    href: "/crm/reports",
    label: "Reports",
    icon: BarChart3,
    permissionKey: "reports:read",
  },
  {
    id: "crm-roles",
    href: "/crm/roles",
    label: "Roles",
    icon: ShieldCheck,
    permissionKey: "roles:read",
  },
  {
    id: "crm-audit",
    href: "/crm/audit",
    label: "Audit",
    icon: ScrollText,
    permissionKey: "audit:read",
  },
  {
    id: "crm-billing",
    href: "/crm/billing",
    label: "Billing",
    icon: CreditCard,
    permissionKey: "billing:read",
    requiresLinkedBrand: true,
  },
];

export const toNavItem = ({
  permissionKey: _permissionKey,
  requiresLinkedBrand: _requiresLinkedBrand,
  ...item
}: CrmSubItem): SidebarNavItem => item;

export const PLATFORM_OVERVIEW_NAV_ITEM: SidebarNavItem = {
  id: "platform-overview",
  href: "/platform",
  label: "Overview",
  icon: LayoutDashboard,
};

export const PLATFORM_NAV_ITEMS: PlatformNavItem[] = [
  {
    id: "brand-applications",
    href: "/platform/brand-applications",
    label: "Brand applications",
    icon: ClipboardList,
    group: "brand-tenants",
  },
  {
    id: "platform-metrics",
    href: "/platform/metrics",
    label: "Tenant metrics",
    icon: Gauge,
    group: "brand-tenants",
  },
  {
    id: "platform-features",
    href: "/platform/features",
    label: "Feature flags",
    icon: SlidersHorizontal,
    group: "platform-settings",
  },
  {
    id: "platform-impersonation",
    href: "/platform/impersonation",
    label: "Impersonation",
    icon: VenetianMask,
    group: "brand-tenants",
  },
  {
    id: "platform-nav-access",
    href: "/platform/nav-access",
    label: "Navigation access",
    icon: Fingerprint,
    group: "platform-settings",
    coFounderOnly: true,
  },
  { id: "products", href: "/products", label: "Products", icon: Package, group: "catalog" },
  {
    id: "collections",
    href: "/collections",
    label: "Collections",
    icon: Layers,
    group: "catalog",
  },
  { id: "categories", href: "/categories", label: "Categories", icon: Tags, group: "catalog" },
  {
    id: "product-types",
    href: "/product-types",
    label: "Garment types",
    icon: Shirt,
    group: "catalog",
  },
  { id: "size-options", href: "/size-options", label: "Sizes", icon: Ruler, group: "catalog" },
  {
    id: "outfit-slot-types",
    href: "/outfit-slot-types",
    label: "Outfit slots",
    icon: Shapes,
    group: "catalog",
  },
  {
    id: "hero-slides",
    href: "/hero-slides",
    label: "Hero slides",
    icon: GalleryHorizontal,
    group: "catalog",
  },
  { id: "orders", href: "/orders", label: "Orders", icon: ShoppingBag, group: "commerce" },
  {
    id: "support",
    href: "/support",
    label: "Support requests",
    icon: LifeBuoy,
    group: "moderation",
  },
  {
    id: "product-reviews",
    href: "/product-reviews",
    label: "Product Reviews",
    icon: Star,
    group: "moderation",
  },
  {
    id: "tag-reviews",
    href: "/tag-reviews",
    label: "Tag reviews",
    icon: ListChecks,
    group: "moderation",
  },
  {
    id: "tag-reports",
    href: "/tag-reports",
    label: "Tag reports",
    icon: Flag,
    group: "moderation",
  },
  {
    id: "content-reports",
    href: "/content-reports",
    label: "Content reports",
    icon: MessageSquareWarning,
    group: "moderation",
  },
  {
    id: "content-browser",
    href: "/content-browser",
    label: "Browse drops",
    icon: Images,
    group: "moderation",
  },
  {
    id: "trending",
    href: "/trending",
    label: "Trending debug",
    icon: TrendingUp,
    group: "growth",
  },
  { id: "users", href: "/users", label: "Users", icon: ShieldAlert, group: "moderation" },
  { id: "creators", href: "/creators", label: "Muses", icon: Users, group: "growth" },
  {
    id: "commissions",
    href: "/commissions",
    label: "Commissions",
    icon: Wallet,
    group: "finance",
  },
  {
    id: "platform-commission",
    href: "/platform-commission",
    label: "Platform commission",
    icon: Percent,
    group: "finance",
  },
  {
    id: "withdraw-requests",
    href: "/withdraw-requests",
    label: "Withdrawal requests",
    icon: BanknoteArrowUp,
    group: "finance",
  },
  {
    id: "bank-accounts",
    href: "/bank-accounts",
    label: "Bank accounts",
    icon: QrCode,
    group: "finance",
  },
  {
    id: "withdraw-policy",
    href: "/withdraw-policy",
    label: "Withdrawal policy",
    icon: Landmark,
    group: "finance",
  },
  {
    id: "financial-rollup",
    href: "/financial-rollup",
    label: "Financial rollup",
    icon: PiggyBank,
    group: "finance",
  },
  {
    id: "coupons",
    href: "/coupons",
    label: "Coupons",
    icon: TicketPercent,
    group: "commerce",
  },
  {
    id: "announcements",
    href: "/announcements",
    label: "Announcements",
    icon: Megaphone,
    group: "growth",
  },
  {
    id: "gamification",
    href: "/gamification",
    label: "Gamification",
    icon: Trophy,
    group: "growth",
    items: [
      {
        id: "gamification-xp-levels",
        href: "/gamification/xp-levels",
        label: "XP & Levels",
        icon: Zap,
      },
      {
        id: "gamification-badges",
        href: "/gamification/badges",
        label: "Badges & Challenges",
        icon: Award,
      },
      {
        id: "gamification-leaderboards",
        href: "/gamification/leaderboards",
        label: "Leaderboards",
        icon: Crown,
      },
      {
        id: "gamification-manual-actions",
        href: "/gamification/manual-actions",
        label: "Manual Actions",
        icon: SlidersHorizontal,
      },
    ],
  },
  {
    id: "delivery-zones",
    href: "/delivery-zones",
    label: "Delivery zones",
    icon: MapPin,
    group: "commerce",
  },
  {
    id: "organizations",
    href: "/organizations",
    label: "Organizations",
    icon: Building2,
    group: "brand-tenants",
  },
  { id: "team", href: "/team", label: "Team", icon: UserCog, group: "brand-tenants" },
  {
    id: "outfit-builds",
    href: "/outfit-builds",
    label: "Outfit builds",
    icon: Blocks,
    group: "moderation",
  },
  {
    id: "platform-switches",
    href: "/platform/switches",
    label: "Feature switches",
    icon: ToggleRight,
    group: "platform-settings",
  },
  {
    id: "platform-settings",
    href: "/platform/settings",
    label: "Limits",
    icon: Settings2,
    group: "platform-settings",
  },
  {
    id: "platform-audit",
    href: "/platform/audit",
    label: "Audit log",
    icon: ScrollText,
    group: "platform-settings",
  },
  {
    id: "platform-jobs",
    href: "/platform/jobs",
    label: "Jobs & health",
    icon: Activity,
    group: "platform-settings",
  },
];

export const PLATFORM_NAV_GROUP_ICONS: Record<PlatformNavGroupKey, SidebarIcon> = {
  "brand-tenants": Building2,
  catalog: LayoutGrid,
  commerce: ShoppingBag,
  moderation: ShieldAlert,
  finance: Wallet,
  growth: TrendingUp,
  "platform-settings": SlidersHorizontal,
};
