export const DEFAULT_RELATIONSHIP_PAGE_SIZE = 25;

export const MAX_RELATIONSHIP_PAGE_SIZE = 100;

export const MAX_RELATIONSHIP_RESULT_WINDOW = 500;

export const RECENT_ACTIVITY_LIMIT = 10;

export const SETTLED_PAYMENT_STATUSES = ["PAID", "DUE", "REFUNDED"] as const;

export const NOT_LINKED_TO_BRAND_REASON = "ORGANIZATION_NOT_LINKED_TO_BRAND";
