export const OUTFIT_SLOT_TYPE_LIMITS = {
  KEY_MIN_LENGTH: 2,
  KEY_MAX_LENGTH: 40,
  LABEL_MIN_LENGTH: 2,
  LABEL_MAX_LENGTH: 40,
  MIN_ITEMS_PER_SLOT: 1,
  MAX_ITEMS_PER_SLOT: 10,
  MAX_LINKED_PRODUCT_TYPES: 50,
  MAX_BLOCKED_SLOT_TYPES: 20,
} as const;

export const OUTFIT_SLOT_TYPE_AUDIT_TARGET_TYPE = "outfit-slot-type";
