export const OFFLINE_ACTION_QUEUE_STORAGE_KEY = "outfiqe-offline-action-queue";

export const MAX_QUEUED_OFFLINE_ACTIONS = 200;

const HOURS_PER_DAY = 24;
const MINUTES_PER_HOUR = 60;
const SECONDS_PER_MINUTE = 60;
const MS_PER_SECOND = 1000;

export const QUEUED_OFFLINE_ACTION_MAX_AGE_MS =
  HOURS_PER_DAY * MINUTES_PER_HOUR * SECONDS_PER_MINUTE * MS_PER_SECOND;
