export type XpActivityType =
  | "LOOK_CREATED"
  | "LOOK_LIKE_RECEIVED"
  | "LOOK_COMMENT_RECEIVED"
  | "LOOK_COMMENTED"
  | "LOOK_SAVED"
  | "USER_FOLLOWED"
  | "PRODUCT_PURCHASED"
  | "SALE_GENERATED"
  | "PRODUCT_TAGGED"
  | "FOLLOWER_MILESTONE"
  | "ACHIEVEMENT_UNLOCKED"
  | "ADMIN_ADJUSTMENT";
