INSERT INTO "nepal_banks" ("id", "name", "code", "type", "created_at", "updated_at")
VALUES
  (gen_random_uuid(), 'Nepal Bank Ltd.', 'A01', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Agricultural Development Bank Ltd.', 'A02', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nabil Bank Ltd.', 'A03', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nepal Investment Mega Bank Ltd.', 'A04', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Standard Chartered Bank Nepal Ltd.', 'A05', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Himalayan Bank Ltd.', 'A06', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nepal SBI Bank Ltd.', 'A07', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Everest Bank Ltd.', 'A08', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Kumari Bank Ltd.', 'A09', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Laxmi Sunrise Bank Ltd.', 'A10', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Citizens Bank International Ltd.', 'A11', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Prime Commercial Bank Ltd.', 'A12', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Sanima Bank Ltd.', 'A13', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Machhapuchhre Bank Ltd.', 'A14', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'NIC Asia Bank Ltd.', 'A15', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Global IME Bank Ltd.', 'A16', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'NMB Bank Ltd.', 'A17', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Prabhu Bank Ltd.', 'A18', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Siddhartha Bank Ltd.', 'A19', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Rastriya Banijya Bank Ltd.', 'A20', 'COMMERCIAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Narayani Development Bank Ltd.', 'B01', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Karnali Development Bank Ltd.', 'B02', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Excel Development Bank Ltd.', 'B03', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Miteri Development Bank Ltd.', 'B04', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Muktinath Bikas Bank Ltd.', 'B05', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Corporate Development Bank Ltd.', 'B06', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Sindhu Bikas Bank Ltd.', 'B07', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Salapa Bikash Bank Ltd.', 'B08', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Green Development Bank Ltd.', 'B09', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Sangrila Development Bank Ltd.', 'B10', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Shine Resunga Development Bank Ltd.', 'B11', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Jyoti Bikas Bank Ltd.', 'B12', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Garima Bikas Bank Ltd.', 'B13', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Mahalaxmi Bikas Bank Ltd.', 'B14', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Lumbini Bikas Bank Ltd.', 'B15', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Kamana Sewa Bikas Bank Ltd.', 'B16', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Saptakoshi Development Bank Ltd.', 'B17', 'DEVELOPMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nepal Finance Ltd.', 'C01', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nepal Share Markets and Finance Ltd.', 'C02', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Goodwill Finance Ltd.', 'C03', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Progressive Finance Ltd.', 'C04', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Janaki Finance Co. Ltd.', 'C05', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Pokhara Finance Ltd.', 'C06', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Multipurpose Finance Ltd.', 'C07', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Samriddhi Finance Company Limited', 'C08', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Capital Merchant Banking & Finance Ltd.', 'C09', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Guheshwori Merchant Banking & Finance Ltd.', 'C10', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'ICFC Finance Ltd.', 'C11', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Manjushree Finance Ltd.', 'C12', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Reliance Finance Ltd.', 'C13', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Gorkhas Finance Ltd.', 'C14', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Shree Investment & Finance Co. Ltd.', 'C15', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Central Finance Ltd.', 'C16', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Best Finance Ltd.', 'C17', 'FINANCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("code") DO NOTHING;
