import path from "node:path";

import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "./src"),
      "@test": path.resolve(import.meta.dirname, "./src/testing"),
    },
  },
  test: {
    coverage: {
      provider: "v8",
      include: [
        "src/features/brand-applications/schemas.ts",
        "src/features/brand-applications/api.ts",
        "src/features/brand-applications/hooks/useInfiniteBrandApplications.ts",
        "src/features/brand-applications/BrandApplicationsPage.tsx",
        "src/features/commissions/CommissionsListSection.tsx",
        "src/features/withdraw-requests/WithdrawRequestsListSection.tsx",
        "src/features/tag-reports/**/*.{ts,tsx}",
        "src/features/content-reports/**/*.{ts,tsx}",
        "src/features/content-browser/**/*.{ts,tsx}",
        "src/features/tag-reviews/**/*.{ts,tsx}",
        "src/components/Logo.tsx",
        "src/features/gamification/designConfig.utils.ts",
        "src/features/gamification/skeletons.tsx",
        "src/features/crm/CompactRowSkeleton.tsx",
        "src/features/gamification/BadgesSection/badgeForm.utils.ts",
        "src/features/gamification/BadgesSection/BadgeFormPage.tsx",
        "src/features/gamification/badgeOptions.constants.ts",
        "src/features/gamification/BadgesSection/DesignStudio/studioLayer.utils.ts",
        "src/features/gamification/BadgesSection/DesignStudio/BadgeDesignSection.tsx",
        "src/features/gamification/BadgesSection/DesignStudio/LayerNumberInput.tsx",
        "src/features/gamification/StatsSection.tsx",
        "src/features/gamification/LeaderboardSection.tsx",
        "src/features/platform-commission/GatewayFeeRatesSection.tsx",
        "src/features/crm/**/*.{ts,tsx}",
        "src/features/product-tour/**/*.{ts,tsx}",
        "src/features/organizations/**/*.{ts,tsx}",
        "src/features/platform-metrics/**/*.{ts,tsx}",
        "src/features/financial-rollup/**/*.{ts,tsx}",
        "src/features/platform-features/**/*.{ts,tsx}",
        "src/features/platform-impersonation/**/*.{ts,tsx}",
        "src/features/platform-nav-access/**/*.{ts,tsx}",
        "src/features/product-types/**/*.{ts,tsx}",
        "src/features/support/schemas.ts",
        "src/features/support/SupportInboxPage.tsx",
        "src/features/orders/OrdersPage.tsx",
        "src/lib/brandsApi.ts",
        "src/lib/useSearchFilter.ts",
        "src/features/auth/AuthContext.tsx",
        "src/features/auth/RegisterInvitePage.tsx",
        "src/features/auth/api.ts",
        "src/features/auth/schemas.ts",
        "src/features/profile/**/*.{ts,tsx}",
        "src/components/ProtectedRoute.tsx",
        "src/components/RedirectingToLogin.tsx",
        "src/lib/bootLoader.ts",
        "src/components/PagePendingSkeleton.tsx",
        "src/components/TableSkeleton.tsx",
        "src/components/CardRowSkeleton.tsx",
        "src/components/ReorderRowSkeleton.tsx",
        "src/components/ReportRowSkeleton.tsx",
        "src/components/ActionRowSkeleton.tsx",
        "src/components/page-skeletons/**",
        "src/components/ProtectedRoute.utils.ts",
        "src/components/AdminSidebar.utils.ts",
        "src/components/adminLanding.ts",
        "src/lib/platformPermissions.ts",
        "src/components/AdminModuleSearch.tsx",
        "src/components/AdminModuleSearch.utils.ts",
        "src/features/notifications/resolveNotificationHref.ts",
        "src/features/notifications/adminNotificationBell.utils.ts",
        "src/features/coupons/**/*.{ts,tsx}",
        "src/features/product-reviews/**/*.{ts,tsx}",
        "src/features/size-options/**/*.{ts,tsx}",
        "src/components/ConfirmModal.tsx",
        "src/components/TextPromptModal.tsx",
        "src/features/users/**/*.{ts,tsx}",
        "src/features/team/**/*.{ts,tsx}",
        "src/features/platform-roles/**/*.{ts,tsx}",
        "src/features/categories/CategoriesPage.tsx",
        "src/features/creators/CreatorsPage.tsx",
        "src/features/hero-slides/HeroSlidesPage.tsx",
        "src/features/platform-commission/BrandExemptionsSection.tsx",
        "src/features/products/ProductsPage.tsx",
        "src/features/products/ProductDetailModal.tsx",
        "src/features/announcements/**/*.{ts,tsx}",
        "src/components/ImpersonationLinkExpired.tsx",
        "src/lib/tenantHost.ts",
        "src/lib/impersonationHandoff.ts",
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
    },
    projects: [
      {
        extends: true,
        test: {
          name: "unit",
          include: ["src/**/*.test.{ts,tsx}"],
          exclude: ["src/**/*.integration.test.{ts,tsx}"],
          environment: "jsdom",
          environmentOptions: { jsdom: { url: "http://localhost:3000" } },
          setupFiles: ["./src/testing/setup.ts"],
        },
      },
      {
        extends: true,
        test: {
          name: "integration",
          include: ["src/**/*.integration.test.{ts,tsx}"],
          environment: "jsdom",
          environmentOptions: { jsdom: { url: "http://localhost:3000" } },
          setupFiles: ["./src/testing/setup.ts", "./src/testing/integration/setup.ts"],
          testTimeout: 15000,
        },
      },
    ],
  },
});
