import path from "node:path";

import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "./src"),
      "@test": path.resolve(import.meta.dirname, "./src/testing"),
    },
  },
  test: {
    coverage: {
      provider: "v8",
      include: [
        "src/features/brand-applications/api/brandApplicationsSchemas.ts",
        "src/features/brand-applications/api/brandApplicationsApi.ts",
        "src/features/brand-applications/hooks/useInfiniteBrandApplications.ts",
        "src/features/brand-applications/components/BrandApplicationsPage.tsx",
        "src/features/commissions/components/CommissionsListSection.tsx",
        "src/features/commissions/components/TierPriceTestBox.tsx",
        "src/features/commissions/components/TierChangeHistory.tsx",
        "src/features/outfit-offers/**/*.{ts,tsx}",
        "src/features/outfit-builds/**/*.{ts,tsx}",
        "src/features/platform-switches/**/*.{ts,tsx}",
        "src/features/platform-settings/**/*.{ts,tsx}",
        "src/features/platform-audit/**/*.{ts,tsx}",
        "src/features/platform-jobs/**/*.{ts,tsx}",
        "src/features/withdraw-requests/components/WithdrawRequestsListSection.tsx",
        "src/features/tag-reports/**/*.{ts,tsx}",
        "src/features/content-reports/**/*.{ts,tsx}",
        "src/features/content-browser/**/*.{ts,tsx}",
        "src/features/tag-reviews/**/*.{ts,tsx}",
        "src/components/Logo.tsx",
        "src/features/gamification/designConfig.utils.ts",
        "src/features/gamification/skeletons.tsx",
        "src/features/crm/components/CompactRowSkeleton.tsx",
        "src/features/gamification/badges/utils/badgeForm.utils.ts",
        "src/features/gamification/badges/components/BadgeFormPage.tsx",
        "src/features/gamification/badgeOptions.constants.ts",
        "src/features/gamification/badges/design-studio/utils/studioLayer.utils.ts",
        "src/features/gamification/badges/design-studio/components/BadgeDesignSection.tsx",
        "src/features/gamification/badges/design-studio/components/LayerNumberInput.tsx",
        "src/features/gamification/stats/components/StatsSection.tsx",
        "src/features/gamification/leaderboards/components/LeaderboardSection.tsx",
        "src/features/platform-commission/components/GatewayFeeRatesSection.tsx",
        "src/features/crm/**/*.{ts,tsx}",
        "src/features/product-tour/**/*.{ts,tsx}",
        "src/features/organizations/**/*.{ts,tsx}",
        "src/features/platform-metrics/**/*.{ts,tsx}",
        "src/features/financial-rollup/**/*.{ts,tsx}",
        "src/features/platform-features/**/*.{ts,tsx}",
        "src/features/platform-impersonation/**/*.{ts,tsx}",
        "src/features/platform-nav-access/**/*.{ts,tsx}",
        "src/features/product-types/**/*.{ts,tsx}",
        "src/features/support/api/supportSchemas.ts",
        "src/features/support/components/SupportInboxPage.tsx",
        "src/features/orders/components/OrdersPage.tsx",
        "src/lib/brandsApi.ts",
        "src/lib/usersApi.ts",
        "src/components/UserSearchField.tsx",
        "src/components/BrandSearchField.tsx",
        "src/lib/useSearchFilter.ts",
        "src/features/auth/components/AuthContext.tsx",
        "src/features/auth/components/RegisterInvitePage.tsx",
        "src/features/auth/api/authApi.ts",
        "src/features/auth/api/authSchemas.ts",
        "src/features/profile/**/*.{ts,tsx}",
        "src/components/ProtectedRoute.tsx",
        "src/components/RedirectingToLogin.tsx",
        "src/lib/bootLoader.ts",
        "src/components/PagePendingSkeleton.tsx",
        "src/components/TableSkeleton.tsx",
        "src/components/CardRowSkeleton.tsx",
        "src/components/ReorderRowSkeleton.tsx",
        "src/components/ReportRowSkeleton.tsx",
        "src/components/ActionRowSkeleton.tsx",
        "src/components/page-skeletons/**",
        "src/components/ProtectedRoute.utils.ts",
        "src/components/AdminSidebar.utils.ts",
        "src/components/adminLanding.ts",
        "src/lib/platformPermissions.ts",
        "src/components/AdminModuleSearch.tsx",
        "src/components/AdminModuleSearch.utils.ts",
        "src/features/notifications/utils/resolveNotificationHref.ts",
        "src/features/notifications/utils/adminNotificationBell.utils.ts",
        "src/features/coupons/**/*.{ts,tsx}",
        "src/features/product-reviews/**/*.{ts,tsx}",
        "src/features/size-options/**/*.{ts,tsx}",
        "src/features/outfit-slot-types/**/*.{ts,tsx}",
        "src/components/ConfirmModal.tsx",
        "src/components/TextPromptModal.tsx",
        "src/features/users/**/*.{ts,tsx}",
        "src/features/team/**/*.{ts,tsx}",
        "src/features/platform-roles/**/*.{ts,tsx}",
        "src/features/categories/components/CategoriesPage.tsx",
        "src/features/creators/components/CreatorsPage.tsx",
        "src/features/hero-slides/components/HeroSlidesPage.tsx",
        "src/features/platform-commission/components/BrandExemptionsSection.tsx",
        "src/features/products/components/ProductsPage.tsx",
        "src/features/products/components/ProductDetailModal.tsx",
        "src/features/announcements/**/*.{ts,tsx}",
        "src/components/ImpersonationLinkExpired.tsx",
        "src/lib/tenantHost.ts",
        "src/lib/impersonationHandoff.ts",
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
    },
    projects: [
      {
        extends: true,
        test: {
          name: "unit",
          include: ["src/**/*.test.{ts,tsx}"],
          exclude: ["src/**/*.integration.test.{ts,tsx}"],
          environment: "jsdom",
          environmentOptions: { jsdom: { url: "http://localhost:3000" } },
          setupFiles: ["./src/testing/setup.ts"],
        },
      },
      {
        extends: true,
        test: {
          name: "integration",
          include: ["src/**/*.integration.test.{ts,tsx}"],
          environment: "jsdom",
          environmentOptions: { jsdom: { url: "http://localhost:3000" } },
          setupFiles: ["./src/testing/setup.ts", "./src/testing/integration/setup.ts"],
          testTimeout: 15000,
        },
      },
    ],
  },
});
