export const IMPERSONATION_DEFAULT_TTL_MINUTES = 30;

export const IMPERSONATION_MAX_TTL_MINUTES = 60;

export const IMPERSONATION_SCOPES = ["read", "write"] as const;

export type ImpersonationScope = (typeof IMPERSONATION_SCOPES)[number];

export const IMPERSONATION_ACTOR_VIA = "impersonation";

export const IMPERSONATION_REAP_INTERVAL_MS = 60 * 60 * 1000;

export const IMPERSONATION_EXCHANGE_CODE_TTL_SECONDS = 60;

const FIFTEEN_MINUTES_MS = 15 * 60 * 1000;

export const IMPERSONATION_REDEEM_RATE_LIMIT_WINDOW_MS = FIFTEEN_MINUTES_MS;

export const IMPERSONATION_REDEEM_RATE_LIMIT_MAX_REQUESTS = 20;
