export const CREATOR_LEADERBOARD_TOP_N = 10;

export const CREATOR_LEADERBOARD_RECOMPUTE_INTERVAL_MS = 15 * 60 * 1000;

export const CREATOR_LEADERBOARD_KEY_RETENTION_SECONDS = 14 * 24 * 60 * 60;

export const TOP_CREATOR_FOLLOWER_WEIGHT = 10;

export const RISING_CREATOR_SURGE_SCORE = 999;

export const GROWTH_PERCENT_MULTIPLIER = 100;
