import type { ExploreProduct, ProductType } from "../ProductCard";

export interface ProductTypeFilter {
  id: "all" | ProductType;
  label: string;
}

export const PRODUCT_TYPE_FILTERS: ProductTypeFilter[] = [
  { id: "all", label: "All" },
  { id: "tops", label: "Tops" },
  { id: "bottoms", label: "Bottoms" },
  { id: "pants", label: "Pants" },
  { id: "headwear", label: "Headwear" },
  { id: "outerwear", label: "Outerwear" },
  { id: "dresses", label: "Dresses" },
];

export const EXPLORE_PRODUCTS: ExploreProduct[] = [
  {
    id: "formal-1",
    categorySlug: "formal",
    type: "tops",
    brand: "Kastha",
    name: "Linen band-collar shirt",
    price: 3450,
    wornByCount: 2,
  },
  {
    id: "formal-2",
    categorySlug: "formal",
    type: "pants",
    brand: "Nepa Threads",
    name: "Pleated wide trouser",
    price: 4200,
    wornByCount: 1,
  },
  {
    id: "formal-3",
    categorySlug: "formal",
    type: "outerwear",
    brand: "Lalitpur Loom",
    name: "Handwoven dhaka waistcoat",
    price: 6800,
    wornByCount: 5,
    lowStock: true,
  },
  {
    id: "formal-4",
    categorySlug: "formal",
    type: "dresses",
    brand: "Aamo",
    name: "Cotton kurta set",
    price: 5100,
    wornByCount: 3,
  },
  {
    id: "formal-5",
    categorySlug: "formal",
    type: "outerwear",
    brand: "Sherpa Supply",
    name: "Quilted overshirt",
    price: 7400,
    wornByCount: 1,
  },
  {
    id: "formal-6",
    categorySlug: "formal",
    type: "outerwear",
    brand: "Thamel Atelier",
    name: "Tailored wool blazer",
    price: 8900,
    wornByCount: 4,
  },
  {
    id: "formal-7",
    categorySlug: "formal",
    type: "tops",
    brand: "Patan Weave",
    name: "Crisp poplin shirt",
    price: 3900,
    wornByCount: 2,
  },
  {
    id: "formal-8",
    categorySlug: "formal",
    type: "bottoms",
    brand: "Newari Co",
    name: "Straight-leg formal trouser",
    price: 4500,
    wornByCount: 1,
  },
  {
    id: "formal-9",
    categorySlug: "formal",
    type: "headwear",
    brand: "Boudha Basics",
    name: "Structured felt hat",
    price: 2800,
    wornByCount: 1,
  },
  {
    id: "formal-10",
    categorySlug: "formal",
    type: "dresses",
    brand: "Kastha",
    name: "Draped satin dress",
    price: 6200,
    wornByCount: 3,
    lowStock: true,
  },

  {
    id: "traditional-1",
    categorySlug: "traditional",
    type: "tops",
    brand: "Nepa Threads",
    name: "Hand-block printed daura",
    price: 5200,
    wornByCount: 4,
  },
  {
    id: "traditional-2",
    categorySlug: "traditional",
    type: "bottoms",
    brand: "Lalitpur Loom",
    name: "Embroidered suruwal",
    price: 4800,
    wornByCount: 2,
  },
  {
    id: "traditional-3",
    categorySlug: "traditional",
    type: "headwear",
    brand: "Aamo",
    name: "Dhaka topi",
    price: 1800,
    wornByCount: 6,
  },
  {
    id: "traditional-4",
    categorySlug: "traditional",
    type: "outerwear",
    brand: "Sherpa Supply",
    name: "Woven pashmina shawl",
    price: 7200,
    wornByCount: 3,
    lowStock: true,
  },
  {
    id: "traditional-5",
    categorySlug: "traditional",
    type: "dresses",
    brand: "Thamel Atelier",
    name: "Printed cotton sari",
    price: 6500,
    wornByCount: 5,
  },
  {
    id: "traditional-6",
    categorySlug: "traditional",
    type: "outerwear",
    brand: "Himal Studio",
    name: "Nepali vest coat",
    price: 5800,
    wornByCount: 2,
  },
  {
    id: "traditional-7",
    categorySlug: "traditional",
    type: "tops",
    brand: "Patan Weave",
    name: "Handloom cotton kurta",
    price: 3600,
    wornByCount: 1,
  },
  {
    id: "traditional-8",
    categorySlug: "traditional",
    type: "pants",
    brand: "Newari Co",
    name: "Pleated ghalek pant",
    price: 4100,
    wornByCount: 1,
  },
  {
    id: "traditional-9",
    categorySlug: "traditional",
    type: "headwear",
    brand: "Boudha Basics",
    name: "Beaded velvet cap",
    price: 2200,
    wornByCount: 3,
  },
  {
    id: "traditional-10",
    categorySlug: "traditional",
    type: "tops",
    brand: "Kastha",
    name: "Festive brocade blouse",
    price: 4700,
    wornByCount: 2,
  },

  {
    id: "streetwear-1",
    categorySlug: "streetwear",
    type: "tops",
    brand: "Aamo",
    name: "Oversized graphic tee",
    price: 2200,
    wornByCount: 8,
  },
  {
    id: "streetwear-2",
    categorySlug: "streetwear",
    type: "pants",
    brand: "Sherpa Supply",
    name: "Cargo utility pant",
    price: 4600,
    wornByCount: 5,
  },
  {
    id: "streetwear-3",
    categorySlug: "streetwear",
    type: "outerwear",
    brand: "Thamel Atelier",
    name: "Boxy denim jacket",
    price: 6900,
    wornByCount: 3,
    lowStock: true,
  },
  {
    id: "streetwear-4",
    categorySlug: "streetwear",
    type: "headwear",
    brand: "Himal Studio",
    name: "Ripstop bucket hat",
    price: 1600,
    wornByCount: 4,
  },
  {
    id: "streetwear-5",
    categorySlug: "streetwear",
    type: "tops",
    brand: "Patan Weave",
    name: "Relaxed fit hoodie",
    price: 3800,
    wornByCount: 6,
  },
  {
    id: "streetwear-6",
    categorySlug: "streetwear",
    type: "bottoms",
    brand: "Newari Co",
    name: "Wide track pant",
    price: 3400,
    wornByCount: 2,
  },
  {
    id: "streetwear-7",
    categorySlug: "streetwear",
    type: "outerwear",
    brand: "Boudha Basics",
    name: "Varsity bomber jacket",
    price: 7800,
    wornByCount: 2,
  },
  {
    id: "streetwear-8",
    categorySlug: "streetwear",
    type: "tops",
    brand: "Kastha",
    name: "Layered mesh top",
    price: 2900,
    wornByCount: 1,
  },
  {
    id: "streetwear-9",
    categorySlug: "streetwear",
    type: "bottoms",
    brand: "Nepa Threads",
    name: "Distressed denim shorts",
    price: 3100,
    wornByCount: 3,
  },
  {
    id: "streetwear-10",
    categorySlug: "streetwear",
    type: "outerwear",
    brand: "Lalitpur Loom",
    name: "Puffer vest",
    price: 5400,
    wornByCount: 1,
  },

  {
    id: "casual-1",
    categorySlug: "casual",
    type: "tops",
    brand: "Aamo",
    name: "Cotton chambray shirt",
    price: 3200,
    wornByCount: 2,
  },
  {
    id: "casual-2",
    categorySlug: "casual",
    type: "pants",
    brand: "Sherpa Supply",
    name: "Relaxed linen pant",
    price: 3900,
    wornByCount: 1,
  },
  {
    id: "casual-3",
    categorySlug: "casual",
    type: "tops",
    brand: "Thamel Atelier",
    name: "Everyday crew sweatshirt",
    price: 3400,
    wornByCount: 4,
  },
  {
    id: "casual-4",
    categorySlug: "casual",
    type: "bottoms",
    brand: "Himal Studio",
    name: "Straight denim jeans",
    price: 4300,
    wornByCount: 3,
  },
  {
    id: "casual-5",
    categorySlug: "casual",
    type: "outerwear",
    brand: "Patan Weave",
    name: "Canvas weekend jacket",
    price: 5600,
    wornByCount: 1,
    lowStock: true,
  },
  {
    id: "casual-6",
    categorySlug: "casual",
    type: "dresses",
    brand: "Newari Co",
    name: "Cotton sundress",
    price: 4100,
    wornByCount: 2,
  },
  {
    id: "casual-7",
    categorySlug: "casual",
    type: "headwear",
    brand: "Boudha Basics",
    name: "Soft knit beanie",
    price: 1500,
    wornByCount: 5,
  },
  {
    id: "casual-8",
    categorySlug: "casual",
    type: "outerwear",
    brand: "Kastha",
    name: "Corduroy overshirt",
    price: 4800,
    wornByCount: 1,
  },
  {
    id: "casual-9",
    categorySlug: "casual",
    type: "tops",
    brand: "Nepa Threads",
    name: "Jersey polo shirt",
    price: 2700,
    wornByCount: 2,
  },
  {
    id: "casual-10",
    categorySlug: "casual",
    type: "bottoms",
    brand: "Lalitpur Loom",
    name: "Utility shorts",
    price: 2400,
    wornByCount: 1,
  },

  {
    id: "minimal-1",
    categorySlug: "minimal",
    type: "tops",
    brand: "Aamo",
    name: "Boxy cotton tee",
    price: 2100,
    wornByCount: 3,
  },
  {
    id: "minimal-2",
    categorySlug: "minimal",
    type: "pants",
    brand: "Sherpa Supply",
    name: "Tapered trouser",
    price: 4400,
    wornByCount: 2,
  },
  {
    id: "minimal-3",
    categorySlug: "minimal",
    type: "outerwear",
    brand: "Thamel Atelier",
    name: "Structured wool coat",
    price: 9200,
    wornByCount: 1,
    lowStock: true,
  },
  {
    id: "minimal-4",
    categorySlug: "minimal",
    type: "dresses",
    brand: "Himal Studio",
    name: "Column midi dress",
    price: 5300,
    wornByCount: 2,
  },
  {
    id: "minimal-5",
    categorySlug: "minimal",
    type: "tops",
    brand: "Patan Weave",
    name: "Seamless knit top",
    price: 2600,
    wornByCount: 4,
  },
  {
    id: "minimal-6",
    categorySlug: "minimal",
    type: "bottoms",
    brand: "Newari Co",
    name: "Straight wide pant",
    price: 3900,
    wornByCount: 1,
  },
  {
    id: "minimal-7",
    categorySlug: "minimal",
    type: "headwear",
    brand: "Boudha Basics",
    name: "Felt bucket hat",
    price: 2000,
    wornByCount: 1,
  },
  {
    id: "minimal-8",
    categorySlug: "minimal",
    type: "outerwear",
    brand: "Kastha",
    name: "Unlined blazer",
    price: 6700,
    wornByCount: 2,
  },
  {
    id: "minimal-9",
    categorySlug: "minimal",
    type: "tops",
    brand: "Nepa Threads",
    name: "Ribbed tank top",
    price: 1900,
    wornByCount: 3,
  },
  {
    id: "minimal-10",
    categorySlug: "minimal",
    type: "bottoms",
    brand: "Lalitpur Loom",
    name: "Cropped wide pant",
    price: 3600,
    wornByCount: 1,
  },

  {
    id: "y2k-1",
    categorySlug: "y2k",
    type: "bottoms",
    brand: "Aamo",
    name: "Low-rise cargo pant",
    price: 3800,
    wornByCount: 5,
  },
  {
    id: "y2k-2",
    categorySlug: "y2k",
    type: "tops",
    brand: "Sherpa Supply",
    name: "Rhinestone baby tee",
    price: 2300,
    wornByCount: 7,
  },
  {
    id: "y2k-3",
    categorySlug: "y2k",
    type: "bottoms",
    brand: "Thamel Atelier",
    name: "Metallic mini skirt",
    price: 3100,
    wornByCount: 3,
    lowStock: true,
  },
  {
    id: "y2k-4",
    categorySlug: "y2k",
    type: "headwear",
    brand: "Himal Studio",
    name: "Furry bucket hat",
    price: 1900,
    wornByCount: 4,
  },
  {
    id: "y2k-5",
    categorySlug: "y2k",
    type: "outerwear",
    brand: "Patan Weave",
    name: "Shrug cardigan",
    price: 3500,
    wornByCount: 2,
  },
  {
    id: "y2k-6",
    categorySlug: "y2k",
    type: "dresses",
    brand: "Newari Co",
    name: "Halter slip dress",
    price: 4600,
    wornByCount: 3,
  },
  {
    id: "y2k-7",
    categorySlug: "y2k",
    type: "tops",
    brand: "Boudha Basics",
    name: "Butterfly print top",
    price: 2500,
    wornByCount: 6,
  },
  {
    id: "y2k-8",
    categorySlug: "y2k",
    type: "bottoms",
    brand: "Kastha",
    name: "Flare denim jeans",
    price: 4700,
    wornByCount: 1,
  },
  {
    id: "y2k-9",
    categorySlug: "y2k",
    type: "outerwear",
    brand: "Nepa Threads",
    name: "Puffy track jacket",
    price: 5900,
    wornByCount: 2,
  },
  {
    id: "y2k-10",
    categorySlug: "y2k",
    type: "tops",
    brand: "Lalitpur Loom",
    name: "Velour tracksuit top",
    price: 3300,
    wornByCount: 1,
  },

  {
    id: "old-money-1",
    categorySlug: "old-money",
    type: "tops",
    brand: "Aamo",
    name: "Cable knit sweater",
    price: 5400,
    wornByCount: 3,
  },
  {
    id: "old-money-2",
    categorySlug: "old-money",
    type: "pants",
    brand: "Sherpa Supply",
    name: "Pleated wool trouser",
    price: 6200,
    wornByCount: 1,
  },
  {
    id: "old-money-3",
    categorySlug: "old-money",
    type: "outerwear",
    brand: "Thamel Atelier",
    name: "Herringbone blazer",
    price: 9800,
    wornByCount: 2,
    lowStock: true,
  },
  {
    id: "old-money-4",
    categorySlug: "old-money",
    type: "tops",
    brand: "Himal Studio",
    name: "Silk button-down shirt",
    price: 6700,
    wornByCount: 1,
  },
  {
    id: "old-money-5",
    categorySlug: "old-money",
    type: "headwear",
    brand: "Patan Weave",
    name: "Tweed flat cap",
    price: 3200,
    wornByCount: 1,
  },
  {
    id: "old-money-6",
    categorySlug: "old-money",
    type: "outerwear",
    brand: "Newari Co",
    name: "Camel wool coat",
    price: 11200,
    wornByCount: 2,
  },
  {
    id: "old-money-7",
    categorySlug: "old-money",
    type: "tops",
    brand: "Boudha Basics",
    name: "Polo neck knit top",
    price: 4800,
    wornByCount: 3,
  },
  {
    id: "old-money-8",
    categorySlug: "old-money",
    type: "bottoms",
    brand: "Kastha",
    name: "Tailored pleat skirt",
    price: 5100,
    wornByCount: 1,
  },
  {
    id: "old-money-9",
    categorySlug: "old-money",
    type: "bottoms",
    brand: "Nepa Threads",
    name: "Cotton twill trouser",
    price: 5300,
    wornByCount: 2,
  },
  {
    id: "old-money-10",
    categorySlug: "old-money",
    type: "outerwear",
    brand: "Lalitpur Loom",
    name: "Quilted riding jacket",
    price: 8600,
    wornByCount: 1,
  },
];
