export const DEFAULT_PLATFORM_AUDIT_PAGE_SIZE = 25;

export const MAX_PLATFORM_AUDIT_PAGE_SIZE = 100;

export const PLATFORM_AUDIT_ACTION = {
  IMPERSONATION_START: "impersonation.start",
  IMPERSONATION_END: "impersonation.end",
  FEATURE_OVERRIDE_SET: "feature.override.set",
  FEATURE_OVERRIDE_CLEARED: "feature.override.cleared",
  TENANT_REQUEST: "tenant.request",
  NAV_ACCESS_HIDDEN_KEYS_SET: "nav-access.hidden-keys.set",
  NAV_ACCESS_CO_FOUNDER_PROMOTED: "nav-access.co-founder.promoted",
  NAV_ACCESS_CO_FOUNDER_DEMOTED: "nav-access.co-founder.demoted",
  USER_SUSPENDED: "user.suspended",
  USER_UNSUSPENDED: "user.unsuspended",
  USER_BANNED: "user.banned",
  USER_UNBANNED: "user.unbanned",
  BRAND_SUSPENDED: "brand.suspended",
  BRAND_UNSUSPENDED: "brand.unsuspended",
  PRODUCT_REVIEW_REMOVED_BY_ADMIN: "product-review.removed-by-admin",
  CREATOR_LOOK_REMOVED_BY_ADMIN: "creator-look.removed-by-admin",
  CREATOR_LOOK_COMMENT_REMOVED_BY_ADMIN: "creator-look-comment.removed-by-admin",
  PLATFORM_ROLE_CREATED: "platform-role.created",
  PLATFORM_ROLE_UPDATED: "platform-role.updated",
  PLATFORM_ROLE_DELETED: "platform-role.deleted",
  PLATFORM_TEAM_MEMBER_ROLE_CHANGED: "platform-team.member-role-changed",
  ADMIN_INVITE_CREATED: "admin-invite.created",
  PLATFORM_SETTING_UPDATED: "platform-setting.updated",
  PLATFORM_SETTING_RESET: "platform-setting.reset",
  FEATURE_FLAG_UPDATED: "feature-flag.updated",
  OUTFIT_SLOT_TYPE_CREATED: "outfit-slot-type.created",
  OUTFIT_SLOT_TYPE_UPDATED: "outfit-slot-type.updated",
  OUTFIT_SLOT_TYPES_REORDERED: "outfit-slot-types.reordered",
  OUTFIT_BUILD_REMOVED_BY_ADMIN: "outfit-build.removed-by-admin",
  OUTFIT_BUILD_COMMENT_REMOVED_BY_ADMIN: "outfit-build-comment.removed-by-admin",
  COMMISSION_TIER_CREATED: "commission-tier.created",
  COMMISSION_TIER_UPDATED: "commission-tier.updated",
  COMMISSION_TIER_DELETED: "commission-tier.deleted",
  ORDER_RETURNED_TO_ORIGIN: "order.returned-to-origin",
  OUTFIT_OFFER_RELEASED_BY_ADMIN: "outfit-offer.released-by-admin",
  OUTFIT_OFFER_REFUNDED_BY_ADMIN: "outfit-offer.refunded-by-admin",
  OUTFIT_OFFER_MARKED_REFUNDED: "outfit-offer.marked-refunded",
} as const;
