import { NotificationType } from "@outfiqe/types";

export const NOTIFICATION_TYPE_LABELS: Record<NotificationType, string> = {
  [NotificationType.LOOK_LIKED]: "Likes on your looks",
  [NotificationType.LOOK_COMMENTED]: "Comments on your looks",
  [NotificationType.COMMENT_REPLIED]: "Replies to your comments",
  [NotificationType.NEW_FOLLOWER]: "New followers",
  [NotificationType.NEW_BRAND_FOLLOWER]: "New brand followers",
  [NotificationType.ACHIEVEMENT_UNLOCKED]: "Badges unlocked",
  [NotificationType.LEVEL_UP]: "Level ups",
  [NotificationType.COMMISSION_EARNED]: "Commissions earned",
  [NotificationType.NEW_ORDER]: "New orders",
  [NotificationType.ORDER_STATUS_CHANGED]: "Order status updates",
  [NotificationType.BRAND_APPLICATION_SUBMITTED]: "New brand applications",
  [NotificationType.PRODUCT_REVIEWED]: "New product reviews",
  [NotificationType.REVIEW_REQUESTED]: "Review reminders",
  [NotificationType.WITHDRAW_REQUEST_APPROVED]: "Withdrawal approvals",
  [NotificationType.WITHDRAW_REQUEST_REJECTED]: "Withdrawal rejections",
  [NotificationType.WITHDRAW_REQUEST_PAID]: "Withdrawal payouts",
  [NotificationType.NEW_MESSAGE]: "New messages",
  [NotificationType.CRM_ITEM_ASSIGNED]: "CRM tasks and tickets assigned to you",
  [NotificationType.SUPPORT_TICKET_CREATED]: "New support requests",
  [NotificationType.SUPPORT_TICKET_ASSIGNED]: "Support requests assigned to you",
  [NotificationType.SUPPORT_TICKET_REPLY]: "Replies on your support requests",
  [NotificationType.SUPPORT_TICKET_RESOLVED]: "Support requests resolved",
  [NotificationType.COUPON_APPROVAL_REQUESTED]: "Coupons awaiting approval",
  [NotificationType.COUPON_BUDGET_ALERT]: "Coupon budget alerts",
  [NotificationType.COUPON_REDEMPTION_FLAGGED]: "Flagged coupon redemptions",
  [NotificationType.PRODUCT_TAG_SUBMITTED]: "Creator tags waiting for review",
  [NotificationType.PRODUCT_TAG_REVIEW_REMINDER]: "Reminders about tags waiting for review",
  [NotificationType.PRODUCT_TAG_APPROVED]: "Your tags approved by brands",
  [NotificationType.PRODUCT_TAG_REJECTED]: "Your tags declined by brands",
  [NotificationType.PRODUCT_TAG_REVOKED]: "Your live tags removed by brands",
};
