export const SUGGESTED_CREATORS_LIMIT = 4;
export const MAX_SUGGESTED_CREATORS_PAGE_SIZE = 30;
export const SUGGESTION_CANDIDATE_POOL_SIZE = 60;
export const MUTUAL_FOLLOW_CANDIDATE_LIMIT = 30;
export const HASHTAG_CANDIDATE_LIMIT = 30;
export const HASHTAG_CANDIDATE_LOOKBACK_DAYS = 45;
export const HASHTAG_CANDIDATE_TOP_TAG_COUNT = 10;

export const SUGGESTION_ENGAGEMENT_LOOKBACK_DAYS = 60;

export const MOMENTUM_SCORE_WEIGHT = 1;
export const FOLLOWER_COUNT_SCORE_WEIGHT = 0.5;

export const NEW_CREATOR_FRESHNESS_WINDOW_DAYS = 14;
export const NEW_CREATOR_FRESHNESS_MULTIPLIER = 1.4;
export const NEW_CREATOR_BASE_SCORE_FLOOR = 0.25;
export const SUGGESTION_SIGNAL_BASE_SCORE_FLOOR = 0.25;

export const MUTUAL_FOLLOW_BOOST_PER_CONNECTION = 0.15;
export const MUTUAL_FOLLOW_BOOST_CAP = 0.9;
export const SUGGESTION_ENGAGED_CREATOR_BOOST = 0.35;
export const SUGGESTION_HASHTAG_BOOST_PER_MATCHING_POST = 0.1;
export const SUGGESTION_HASHTAG_MATCHING_POST_CAP = 5;
export const SUGGESTION_HASHTAG_BOOST_CAP = 0.4;

export const MIN_MOMENTUM_DISCOVERY_SLOTS = 2;
export const SUGGESTION_ROTATION_TIE_BAND = 0.15;
