export const OUTFIT_ADMIN_LIMITS = {
  LIST_DEFAULT_PAGE_SIZE: 20,
  LIST_MAX_PAGE_SIZE: 50,
  HISTORY_PAGE_SIZE: 50,
  SEARCH_MAX_LENGTH: 80,
  REASON_MIN_LENGTH: 3,
  REASON_MAX_LENGTH: 500,
  METRICS_DEFAULT_WEEKS: 12,
  METRICS_MAX_WEEKS: 52,
} as const;

export const OUTFIT_ADMIN_AUDIT_TARGET_TYPE = "Outfit";

export const METRICS_TIME_ZONE = "Asia/Kathmandu";

export const BUILD_ORDER_KIND = {
  FULL_SET: "FULL_SET",
  PICKED_ITEMS: "PICKED_ITEMS",
} as const;
