export const CHAT_CONTACT_SEARCH_RESULT_LIMIT = 20;

export const CHAT_BLOCKS_DEFAULT_PAGE_SIZE = 20;
export const CHAT_BLOCKS_MAX_PAGE_SIZE = 50;

export const CHAT_SETTINGS_RATE_LIMIT_NAMESPACE = "chat-settings";
export const CHAT_SETTINGS_RATE_LIMIT_WINDOW_MS = 5 * 60 * 1000;
export const CHAT_SETTINGS_RATE_LIMIT_MAX_REQUESTS = 20;

export const CHAT_SOCKET_CONSUMER_GROUP = "socket-broadcast";

export const CONVERSATIONS_DEFAULT_PAGE_SIZE = 20;
export const CONVERSATIONS_MAX_PAGE_SIZE = 50;

export const MESSAGES_DEFAULT_PAGE_SIZE = 30;
export const MESSAGES_MAX_PAGE_SIZE = 100;
export const MESSAGE_MAX_LENGTH = 4000;
export const MESSAGE_MAX_ATTACHMENTS = 6;

export const MESSAGE_SEND_RATE_LIMIT_NAMESPACE = "message-send";
export const MESSAGE_SEND_RATE_LIMIT_WINDOW_MS = 60 * 1000;
export const MESSAGE_SEND_RATE_LIMIT_MAX_REQUESTS = 30;
